### ISSUE TITLE
Resolve Atom+Molecule conflict

### ISSUE THREAD

**Issue by jbwheatley** [TypeChecked/alphabet-soup#37]
I as a user define `implicit val atomF: Atom[F[Foo]] = Atom[F[Foo]]`, which will compile. 
If I happen to have a molecule in scope - `implicit def m[A]: Molecule[F, A]...` the failure point for the algorithm will be in SelectFromAtomised. It would be more informative to the user if the point of failure was the creation of the atom `atomF` (much like done for DefaultAtom). 

Further, you cannot use atoms in mixing of type `Atom[Option[Foo]]` or `Atom[List[Foo]]` at all due to the automatic pick up the molecules in the Molecule companion, and again the compilation error obfuscates the fact that atoms and molecules can't exists side-by-side.

**Comment by jdrphillips** [comment]
I think you should be able to override molecule behaviour with atomic behaviour. You might not always want the content of your molecule to be viewed as discrete data.

That was always the intention but clearly it doesn't work

**Comment by jbwheatley** [comment]
so one solution to this is to de-prioritise the molecule steps of SelectFromAtomised etc. 

The other problem is that you cannot create and use a `DefaultAtom` for `List[_]` or `Option[_]` due to the automatic pick-up of the molecules. We could move those molecules out of the companion object?

**Comment by jdrphillips** [comment]
I don't remember why `DefaultAtom`s are forbidden if there is a `Molecule` instance! 

The provided molecules should definitely stay in the companion object, any other choices made should work around that design.

I think de-prioritising the molecule steps will make it possible to have default atoms and molecules present for the same type.

**Comment by jbwheatley** [comment]
I can do this later today 😎

**Comment by jdrphillips** [comment]
Renamed this issue

**Comment by jdrphillips** [comment]
Resolved in #38
