### ISSUE TITLE
README Updates

### ISSUE THREAD

**Issue by jdrphillips** [TypeChecked/alphabet-soup#6]
- Remove section about the future
- Remove publishLocal instructions
- Link to https://medium.com/@jdrphillips/alphabet-soup-type-level-transformations-eb60918af35d as a whistle-stop tour of the concepts involved in the algorithm

**Comment by aeons** [comment]
Also mention that the lib is published on maven :)

**Comment by jdrphillips** [comment]
Have done so - thanks!
